### ISSUE TITLE
$isDevMode for installForVendors

### ISSUE THREAD

**Issue by jakestubbz** [eloquent/composer-npm-bridge#14]
I'd like `installForVendors()` of `NpmBridge` to install dependencies based on the value of composers `isDevMode` event method, as `install()` of `NpmBridge` does.

As you'll see below, it passes `false` each time it calls `client->install()`:

```php
    private function installForVendors($composer)
    {
        $this->io->write(
            '<info>Installing NPM dependencies for Composer dependencies</info>'
        );

        $packages = $this->vendorFinder->find($composer, $this);

        if (count($packages) > 0) {
            foreach ($packages as $package) {
                $this->io->write(
                    sprintf(
                        '<info>Installing NPM dependencies for %s</info>',
                        $package->getPrettyName()
                    )
                );

                $this->client->install(
                    $composer->getInstallationManager()
                        ->getInstallPath($package),
                    false
                );
            }
        } else {
            $this->io->write('Nothing to install');
        }
    }
```

I'm wondering if this was a decision made intentionally, or is it to be considered a bug? If the latter, I can PR a fix if there's interest.

**Comment by ezzatron** [comment]
This is intentional, as this mimics how Composer itself behaves. Even when in "dev mode", Composer will not install the dev dependencies of your package's dependencies. Another way of saying this would be that Composer only installs dev dependencies of the root project. [Relevant section from the Composer docs](https://getcomposer.org/doc/04-schema.md#require-dev) (emphasis mine):

> require-dev ([root-only](https://getcomposer.org/doc/04-schema.md#root-package)) [#](https://getcomposer.org/doc/04-schema.md#require-dev)
>
> Lists packages required for developing this package, or running tests, etc. The dev requirements of the **root package** are installed by default. Both install or update support the --no-dev option that prevents dev dependencies from being installed.

If the packages you depend on cannot function without one of their `require-dev` dependencies, then that dependency is probably not a `require-dev` dependency, and should be promoted to `require`, or perhaps alternatively should be a dev dependency of the root project.

**Comment by jakestubbz** [comment]
Thanks for taking the time to explain that @ezzatron, makes perfect sense. I'm attempting to build a React application (wrapped in a composer module) on composer install - I can find a way make this work with composers behaviour now I understand it. Thanks again!

I'll mark this issue as closed.

**Comment by ezzatron** [comment]
No worries, glad you found a solution that works for you!
