### ISSUE TITLE
Support question: Disable the bridge with a composer parameter?

### ISSUE THREAD

**Issue by koehnlein** [eloquent/composer-npm-bridge#18]
Hi everybody,

I use your bridge in some of my projects and it works fine. But now I have a new problem, in my GitLab CI pipeline.

I run PHP tests and need to install composer packages for this. When I install them with `composer install` the bridge starts doing it's job. Is there a way to install the composer packages with suppressing the NPM bridge, e.g. a command like `composer install --no-npm`?

**Comment by ezzatron** [comment]
Currently, the only way you can do this whilst using this plugin is `composer install --no-plugins`.

If this were to be added as a feature, it would probably have to be done via an environment variable like `COMPOSER_NPM_BRIDGE_DISABLE=1`, because it looks like Composer's plugin system lets you add new commands, but not global CLI options like `--no-npm`.

If we're talking about an "end project" package here, the other option is to *not* use this plugin at all, and use `make` or some other task runner / build system to install only the appropriate dependencies for specific tasks. However, if we're talking about a package that gets brought in as a dependency, this is less feasible.

P.S. The `--dev` option basically does nothing - Composer installs dev dependencies by default. In order to *not* install dev dependencies you need to use `--no-dev`.

**Comment by koehnlein** [comment]
Thanks for your feedback. Unfortunately, disabling all plugins is not an option for me :-/ But if you will integrate an environment variable one day in the future, it would be great for me.

P.S. You're right. My real code does not contain the `--dev` parameter for install commands. ;-)

**Comment by ezzatron** [comment]
Released in [4.1.0](https://github.com/eloquent/composer-npm-bridge/releases/4.1.0)
