### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by phillipmadsen** [eloquent/composer-npm-bridge#9]
on composer install and on composer update
 [Eloquent\Composer\NpmBridge\Exception\NpmCommandFailedException]
 Execution of '\'/usr/bin/npm\' \'install\'' failed.

**Comment by ezzatron** [comment]
This project is largely abandoned now, because of Composer changes that broke its core functionality (see #8). I've been meaning to update the README to reflect this, apologies for that.

That said, I may be able to offer some advice if you can paste some more detailed error information. I believe you'll get a full stack trace if you run Composer in verbose (`-v`) mode.

**Comment by phillipmadsen** [comment]
Thanks, the problem i was having was using a vagrant box intall of homestead which is not very friendly with windows and laravel-elixir which uses both bower and gulp. i was hoping this plugin would make it a native node install that would be easier to incorporate the node modules without all the runtime errors. I just used the old way of doing it through apt-get remove purge nodejs then reinstalled a fresh version through apt-get which seems to work for the time being but thanks for trying.
